package org.hopto.jfbennatt.pillars;

public class QuadraticException extends Exception {
	// This is an example of inheritance because QuadraticException inherits from
	// Exception
	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -2673398029280598732L;

	/**
	 * Message for there being no real solutions
	 */
	public static final String NO_REAL_SOLUTIONS = "There are no real solutions to this quadratic";
	/**
	 * Message for there being infinite solutions
	 */
	public static final String INFINITE_SOLUTIONS = "There are infinite solutions to this quadratic";
	/**
	 * Message for when trying to get a y-intercept when from a trivial quadratic
	 * function (f(x) = 0).
	 */
	public static final String NO_Y_INTERCEPT = "There are infinite solutions, thus no y-intercept";

	/**
	 * Returns the default Exception with no message.
	 */
	public QuadraticException() {
		super();
	}

	/**
	 * Returns an Exception with the given message
	 * 
	 * @param message message printed to screen when exception is thrown.
	 */
	public QuadraticException(final String message) {
		// this is polymorphism because it overloads the constructor for
		// QuadraticException
		super(message);
	}

}
