package com.revature.banking;

public class TransactionException extends Exception {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -8489970867435153179L;

	/**
	 * Only constructor given because you must give a message describing this
	 * exception (because this message is used to give feedback to the user).
	 * 
	 * @param message Message explaining what went wrong.
	 */
	public TransactionException(final String message) {
		super(message);
	}
}
