server:
  port: 2444
  
spring:
  application:
    name: customer-service
    
eureka:
    instance:
      lease-renewal-interval-in-seconds: 2
    client:
      fetch-registry: true
      service-url:
        defaultZone: http://${CA}:8761/eureka

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream