package com.revature.bank.exceptions;

/**
 * These exceptions are for when the bank is improperly being populated (e.g.
 * you try and add a duplicate account).
 * 
 * @author benna
 *
 */
public class IllegalUpdateException extends RuntimeException {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -7766694831100693585L;

	public IllegalUpdateException() {
		super();
	}

	public IllegalUpdateException(final String message) {
		super(message);
	}
}
