package com.revature.bank.exceptions;

public class InvalidPasswordException extends Exception {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 3583144974727124587L;

	public InvalidPasswordException() {
		super();
	}

	public InvalidPasswordException(final String password) {
		super("Invalid Password: " + password);
		// TODO probably should come back to this and attempt to give a more descriptive
		// reason
	}

}
