package com.revature.bank.exceptions;

public class InvalidUserNameException extends Exception {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -3896957618723213470L;

	public InvalidUserNameException() {
		super();
	}

	public InvalidUserNameException(final String username) {
		super("Invalid User Name: " + username);
		// TODO Probably should come back to this and attempt to give a more descriptive
		// reason
	}
}
