package com.revature.bank.exceptions;

public class PopulationException extends Exception {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -5115370319891239045L;

	public PopulationException() {
		super();
	}

	public PopulationException(final String message) {
		super(message);
	}

}
