package com.revature.banking.application;

public class IllegalChoiceException extends Exception {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 2688984681435361219L;

	/**
	 * This is the only constructor provided because the message is used by the
	 * BankingApplication to give the user feedback.
	 * 
	 * @param message
	 */
	public IllegalChoiceException(final String message) {
		super(message);
	}
}
