server:
  port: 8765

spring:
  application:
    name: gateway-server

zuul:
  routes:
    account:
      path: /accounts/**
      service-id: account-service #or is it serviceId
      strip-prefix: false
    customer:
      path: /**
      service-id: customer-service
      strip-prefix: false